#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Standart, System and Third Party
import time

# ROS
import rospy

# Robonomics communication
from robonomics_msgs.msg import Offer, Demand
from ethereum_common.msg import Address, UInt256
from ethereum_common.srv import Accounts, BlockNumber
from ipfs_common.msg import Multihash

# AIRA
from robonomics_liability.msg import Liability


class TraderNode:
    """
    A node used to listen a market and react by defined strategy.

    Usage
    =====
    TraderNode.act - a place for your strategy to react on incomming offers and demands
    By default it use reactive strategy to act on incoming offers and demands. If you would like to
    change it, please take a look on TraderNode.on_incoming_* functions.

    Important note
    ==============
    Please ensure you've made an *approve* on *factory.<version>.robonomics.eth* contract if you
    publish demands. Take a look on *ethereum_common* package for appropriate services.

    API
    ===

    Parameters
    ----------
    ~model : str
        Agent model IPFS hash
    ~token : str
        Contract address of token agent recieve as payment
    ~lot_lifetime : int
        How many blockcs agent's offers and demands are valid

    Subscribed Topics
    -----------------
    /liability/infochan/incoming/demand : robonomics_msgs/Demand
    /liability/infochan/incoming/offer : robonomics_msgs/Offer

    Services Called
    ---------------
    /eth/current_block
    /eth/accounts

    """

    def __init__(self):
        rospy.init_node('trader')
        rospy.loginfo('Launching trader node...')

        rospy.wait_for_service('/eth/current_block')
        rospy.wait_for_service('/eth/accounts')
        self.accounts = rospy.ServiceProxy('/eth/accounts', Accounts)()
        rospy.loginfo(str(self.accounts)) # AIRA ethereum addresses

        self.signing_offer = rospy.Publisher('/liability/infochan/eth/signing/offer', Offer, queue_size=128)

        rospy.Subscriber('/liability/ready', Liability, self.on_new_liability)

        rospy.loginfo('Trader node launched.')

        self.make_offer()

    def on_new_liability(self, msg):
        self.make_offer()
        rospy.loginfo("Got new liability %s", msg.address)

    def make_deadline(self):
        lifetime = int(rospy.get_param('~order_lifetime'))
        deadline = rospy.ServiceProxy('/eth/current_block', BlockNumber)().number + lifetime
        return str(deadline)

    def make_offer(self):
        rospy.loginfo('Making offer...')

        offer = Offer()
        offer.model = Multihash()
        offer.model.multihash = rospy.get_param('~model')
        offer.token = Address()
        offer.token.address = rospy.get_param('~token')
        offer.objective = Multihash()
        offer.objective.multihash = rospy.get_param('~objective')
        offer.cost = UInt256()
        offer.cost.uint256 = str(rospy.get_param('~cost'))
        offer.lighthouse = Address()
        offer.lighthouse.address = rospy.get_param('~lighthouse')
        offer.validator = Address()
        offer.validator.address = '0x0000000000000000000000000000000000000000'
        offer.lighthouseFee = UInt256()
        offer.lighthouseFee.uint256 = '0'
        offer.deadline = UInt256()
        offer.deadline.uint256 = self.make_deadline()

        self.signing_offer.publish(offer)
        rospy.loginfo(offer)

        while True:
            current_block = rospy.ServiceProxy('/eth/current_block', BlockNumber)().number
            # rospy.loginfo(current_block)
            # rospy.loginfo(offer.deadline.uint256)
            if current_block > int(offer.deadline.uint256):
                self.make_offer()
            time.sleep(15)

    def spin(self):
        rospy.spin()

if __name__ == '__main__':
    TraderNode().spin()
